Feature/frontend/fix issue
kevinlizh1992/rtterror pull request #52
Opened 2022-03-08 04:12 UTC by kimchhengheng

# Description

_Briefly explain what the PR does._

Resolve the frontend issue of the Service and Employee

# Related Jira Issue (ID/URL)

[Sample Link Name](URL)

# Related GitHub Issues

- This fixes #5.

# Checklist

- [ ] Code compiles correctly
- [ ] Code is covered by current tests or new tests
- [ ] Code is formatted correctly
- [ ] Extended the README / documentation, if necessary

---

# Comment/Discussion

_Add anything else._

2022-03-08 07:13 UTC, NJLprograms approved these changes
Sonarcloud quality passed and code is very readable! You should update the pr description to mention what this fixes.

2022-03-10 00:49 UTC, kevinlizh1992 commented
@kimchhengheng just a small comment, the employee phone number bugs out when you enter, say 514 and a dash, it autogenerates a bunch of parentheses when you try to erase the phone number, the only way is to close the window and re-add the employee

2022-03-10 00:55 UTC, kevinlizh1992 approved these changes

2022-03-10 00:56 UTC, yuxiang-zhang requested changes
Changes look good, only 1 little change is needed to meet the PO requirements.

2022-03-10 00:56 UTC, yuxiang-zhang commented on frontend/components/service/durationPriceItem.js
> +                            max={120}
The PO said maximum can go to 5-6 hours.

2022-03-10 00:56 UTC, yuxiang-zhang commented on frontend/components/service/index.js
> +    const { serviceListData, toggleBlocked, deleteService, refresh, setRefresh , comboList} = props;
doesn't look like the code has been formatted correctly

2022-03-10 00:56 UTC, yuxiang-zhang commented on frontend/components/service/serviceCardRow.js
> +        // if (step === 0 && !item.hasOwnProperty('services')) {
We can remove the commented code, and retrieve later via version control if needed.

2022-03-10 03:33 UTC, kimchhengheng commented
> @kimchhengheng just a small comment, the employee phone number bugs out when you enter, say 514 and a dash, it autogenerates a bunch of parentheses when you try to erase the phone number, the only way is to close the window and re-add the employee

fixed the issue related to that

2022-03-10 03:35 UTC, kimchhengheng commented
resolve the conflict.

2022-03-10 04:56 UTC, yuxiang-zhang approved these changes

2022-03-10 05:01 UTC, merged