customize employee_id && client details for appointment queries
kevinlizh1992/rtterror pull request #62
Opened 2022-03-27 02:12 UTC by Alex-DSJ

# Description

This add a feature to allow the user to customized the employee_id
This will provide client details for appointment queries

---

# Related Jira Issue (ID/URL)

N/A

# Related GitHub Issues

- This fixes #60, #61.

# Checklist

- [X] Code compiles correctly
- [X] Code is covered by current tests or new tests
- [X] Code is formatted correctly
- [X] Extended the README / documentation, if necessary

---

# Comment/Discussion

modification based on new requirements from stakeholders and frontend developers.

2022-03-30 00:36 UTC, yuxiang-zhang requested changes

2022-03-30 00:36 UTC, yuxiang-zhang commented on backend/src/models/syncTables.ts
> +      Customer.sync({ alter: true }),
I suggest aliasing `Customer as CustomerModel` for consistency.

2022-03-30 00:36 UTC, yuxiang-zhang commented on backend/src/models/syncTables.ts
>      await Appointment.sync({ alter: true });
This model will not be used to store Appointment instances. All code (e.g. `appointment.model.ts`) related to this model are effectively *dead code* and should therefore be removed.

2022-03-30 00:36 UTC, yuxiang-zhang commented on backend/src/services/appointment-service.ts
> +      return;
The frontend expects a return value that can be parsed as JSON. Returning `void` as response will cause the frontend `util.http` method to crash.

2022-04-01 04:50 UTC, NJLprograms approved these changes

2022-04-01 18:02 UTC, yuxiang-zhang approved these changes

2022-04-01 18:02 UTC, merged